---
tags:
- pdep
- guia1
- basico
- aritmetica
- tuplas
- aplicacionParcial
layout: input_right
editor: code
type: problem
extra_visible: false
manual_evaluation: false
choices: []
name: cuentaBizarra
